baseURL = 'https://blog.meterai.digital/'
languageCode = 'id-ID'
title = 'Artikel Meterai Digital'
theme = 'mediumish-gohugo-theme'
summaryLength = 25
copyright = 'PT Aksatera Teknologi Nusadipa'
enableEmoji = true

[params]
  logo = "/images/logo-meterai-digital.png"
  description = "Artikel dan Panduan"
  favicon = "/favicon.ico"
  author_thumb = "https://avatars.githubusercontent.com/aksatera"

[params.author]
  name = "Tim Meterai Digital"
  thumbnail = "https://avatars.githubusercontent.com/aksatera"
  description = "PT Aksatera Teknologi Nusadipa"

[params.index]
  picture = "/images/logo-meterai-digital.png"
  title = "Artikel Meterai Digital"
  subtitle = "Tutorial & Panduan E-Meterai"
  alertbar = false

[params.social]
  # github = "aksatera"

[markup.goldmark.renderer]
  unsafe = true

## Main Menu
[[menu.main]]
    name = "Semua Artikel"
    weight = 100
    identifier = "blog"
    url = "/"
[[menu.main]]
    name = "Meterai Digital"
    identifier = "meterai"
    weight = 200
    url = "https://meterai.digital"
