baseURL = 'https://blog.meterai.digital/'
languageCode = 'id-ID'
title = 'Meterai Digital Blog'
theme = 'mediumish-gohugo-theme'
summaryLength = 25
copyright = 'PT Aksatera Teknologi Nusadipa'
enableEmoji = true

[params]
  logo = "/images/logo.png"
  description = "Tutorial & Knowledge Base Meterai Digital"

[params.author]
  name = "Tim Meterai Digital"
  thumbnail = "/images/author.png"
  description = "PT Aksatera Teknologi Nusadipa"

[params.index]
  title = "Meterai Digital Blog"
  subtitle = "Tutorial & Panduan E-Meterai"
  alertbar = false
  mdtext = '''
Selamat datang di **Meterai Digital Blog** — tempatnya tutorial, panduan, dan knowledge base seputar E-Meterai di Indonesia.
'''

[params.social]
  github = "aksatera"

[markup.goldmark.renderer]
  unsafe = true

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/"
[[menu.main]]
    name = "Meterai Digital"
    weight = 200
    identifier = "meterai"
    url = "https://meterai.digital"
