apiVersion: v1
kind: Secret
metadata:
  name: blog-credentials
  namespace: mdi
type: Opaque
stringData:
  auth: |
    patria:$apr1$NnRfXcRu$RKND3rVlqrjoC8JGkXeJ81
    nuzul:$apr1$lp6hkMQQ$IwQ2UqSOWjBSX7uGFykMr.
  GITHUB_PAT: "****"
  HUGO_PAT: "****"
