backend:
  name: github
  repo: aksatera/meterai-digital-blog
  branch: main
  base_url: https://api.github.com

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Tim Meterai Digital" }
      - { label: "Tags", name: "tags", widget: "list", default: ["tutorial"] }
      - { label: "Body", name: "body", widget: "markdown" }
